### ISSUE TITLE
Feature Request - Extract Tasks from selection into OmniFocus

### ISSUE THREAD

**Issue by mattsmallman** [lizard-heart/obsidian-to-omnifocus#1]
@lizard-heart - This plugin is just what I have been looking for. Thanks so much.

One minor request - Is it possible to just take the currently selected text and parse that for tasks - 

Reason: I use the task markdown format several different ways in meeting notes:
- to identify participants and whether they attended. 
- to remember to ask questions or cover particular points in the agenda and meeting notes
- at the end in my Actions section to follow up with

I only really want these last tasks in Omnifocus but get all of them

I think this requires a new command with : view.editor.getSelection() as the source but don't know how to propose a change to your code.

**Comment by mattsmallman** [comment]
Ok - I just decided to give it a go and have it working in my local with a pull request (my first ever so be gentle) here: #2

**Comment by lizard-heart** [comment]
Thanks! I refactored it since your initial pull request repeated a lot of code twice, but it is now merged. I appreciate the contribution!
