### ISSUE TITLE
Due Date AutoFill

### ISSUE THREAD

**Issue by jamesg546** [lizard-heart/obsidian-to-omnifocus#11]
A useful feature would be if the due date for the task was auto filled in the OmniFocus popup. It is easy to hit tab to set the project, tags, etc., but you have to click to select the date. Great plugin though. I use it all the time because I take notes in Obsidian for work and this makes it easy to send to OmniFocus where I manage my tasks. Thank you for developing it.

**Comment by lizard-heart** [comment]
Thank you for the suggestion. This should be merged in now.

**Comment by jamesg546** [comment]
Awesome. Thank you

**Comment by jamesg546** [comment]
I think that something broke the plugin. It fails when updating.

**Comment by lizard-heart** [comment]
@jamesg546 Yep. I needed to publish the new release. It should work now.
