### ISSUE TITLE
Link to note in task description incorrectly formatted when vault has spaces in its names

### ISSUE THREAD

**Issue by orizonlabs** [lizard-heart/obsidian-to-omnifocus#4]
When a task is created, an URI link to the Obsidian task origin location is added as task description in Omnifocus. If the vault has spaces in its name, then these spaces are not translated to `%20` but kept as ` ` which creates a broken link.

**Comment by yoghurtdewdew** [comment]
I have similar problems. Emoji in name of a folder will break the obsidian url. Hope to support the uri URL.

**Comment by dorich** [comment]
I have the same problem. Spaces in the vault title appear as spaces in the URI Link.

**Comment by shabegom** [comment]
Opened a PR to fix the spaces in vault name issue. It doesn't handle emoji or other characters. I'm not sure what an emoji gets encoded as for a URI...

**Comment by yoghurtdewdew** [comment]
Hi I wonder if Advanced URI could be used so the name would not be a problem?
