### ISSUE TITLE
Mac Not Functioning

### ISSUE THREAD

**Issue by dorich** [lizard-heart/obsidian-to-omnifocus#7]
This plugin doesn't appear to be working on the Mac. I've installed from the Browser and completed the manual installation but nothing appears in the Command Panel. Tried setting a hot key but that doesn't produce any activity.

**Comment by cybertunnel** [comment]
Did you verify the plugin is enabled?

**Comment by lizard-heart** [comment]
This should be fixed. Let me know if you are still having problems.
