### ISSUE TITLE
Not working as expected on Ipad-IOS

### ISSUE THREAD

**Issue by Attempto001** [lizard-heart/obsidian-to-omnifocus#8]
On the mac it will take up multiple tasks and send them to Omnifocus and check them all off. 
In IOS on the Ipad however it only takes the first task and ignores all the other ones. But they are all marked off. 
Can that bi fixed? It would be a great help!

**Comment by lizard-heart** [comment]
Should be fixed now. Let me know if it's still not working.

**Comment by Attempto001** [comment]
Hi and thank you so much for the attempt of fixing the problem. 
Obsidian was not able to load the update of the plugin. 
I then tried to uninstall und install again, that also is not possible. Installation failed. 
Obsidian is up to date and I tried it on IOS and OS. 
Anything I can do on my side? 

Thanks for your help and best regards 
Christopher

**Comment by lizard-heart** [comment]
@Attempto001 thanks for pointing this out. I just needed to publish the new release. Should work fine now. Please let me know if there are still problems.
